services:
  express:
    build:
      context: .
      dockerfile: ./server/DockerFile
    container_name: express
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - ./server/:/app/
    depends_on:
      - db
  db:
    image: mysql:5.7.37
    container_name: db
    shm_size: 128mb
    expose:
      - 3306
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "biblioteka"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "123"
      MYSQL_ROOT_PASSWORD: "rootpass"
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/site
    ports:
      - "80:80"
      - "443:443"
  adminer:
    image: adminer
    ports:
      - 8080:8080